on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
        - main
        - dev

name: Go1 Build Catkin
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    
    steps:
      - name: run
        uses: ./.github/workflows/go1catkin
