name: Go1 Build Catkin

on:
  pull_request:
    branches:
      - dev
    


jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: run
        uses: ./.github/workflows/go1catkin
